my_project/my_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = i18n_patterns(
    path("i18n/", include("django.conf.urls.i18n")),
    path("admin/", admin.site.urls),
    path("", include("my_site.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_project/my_site/urls.py
from django.urls import path
from my_site.views import *
from django.contrib.auth import views as auth_views
from .forms import LoginForm
from django.views.i18n import set_language


app_name = "my_site"

urlpatterns = [
    path("", property_index_page, name="index"),
    path("property/<int:pk>/", property_detail_view, name="property_detail_view"),
    path(
        "property/for_sale/",
        property_for_sale_list_view,
        name="property_for_sale_list_view",
    ),
    path(
        "property/for_rent/",
        property_for_rent_list_view,
        name="property_for_rent_list_view",
    ),
    path("contacts/", contacts, name="contacts"),
    path("thank_you/", thank_you, name="thank_you"),
    path("search-result/", search_result, name="search_result"),
    path("signup/", signup, name="signup"),
    path(
        "user_login/",
        auth_views.LoginView.as_view(
            template_name="my_site/login.html", authentication_form=LoginForm
        ),
        name="user_login",
    ),
    path("accounts/profile/<int:pk>/", profile, name="profile"),
    path("edit_profile/", edit_profile, name="edit_profile"),
    path("bookmark/<int:pk>", bookmark, name="bookmark"),
    path("favorites/<int:pk>", favorites, name="favorites"),
    path("blog/", blog, name="blog"),
    path("team/", team, name="team"),
    path("set-language/", set_language, name="set_language"),
    path("exchange_rates/", exchange_rates, name="exchange_rates"),
    path("dashboard/", dashboard, name="dashboard"),
    path("new_property/", new_property, name="new_property"),
    path("edit_property/<int:pk>/", edit_property, name="edit_property"),
    path("delete_property/<int:pk>/", delete_property, name="delete_property"),
    path("new_blog_post/", new_blog_post, name="new_blog_post"),
    path("edit_blog_post/<int:pk>/", edit_blog_post, name="edit_blog_post"),
    path("delete_blog_post/<int:pk>/", delete_blog_post, name="delete_blog_post"),
    path("new_team_mate/", new_team_mate, name="new_team_mate"),
    path("edit_team_mate/<int:pk>/", edit_team_mate, name="edit_team_mate"),
    path("delete_team_mate/<int:pk>/", delete_team_mate, name="delete_team_mate"),
    path("dashboard/properties/", dash_properties, name="dash_properties"),
    path("dashboard/blog/", dash_blog, name="dash_blog"),
    path("dashboard/team/", dash_team, name="dash_team"),
]

my_project/my_site/models.py
from django.db import models
from django.conf import settings
from django.utils.translation import gettext_lazy as _

from custom_user.models import User

from PIL import Image

from config import (
    HEATING_CHOICES,
    PROPERTY_TYPES,
    IL_LIST,
    ANTALYA_DIST_LIST,
    DEAL_TYPES,
    PARKING_TYPE,
    ELEVATOR,
    FRONTAGE,
    ISKAN,
    EXPERTISE,
    RESIDENCE_PERMIT,
)

from .translation import translate


class Category(models.Model):
    name = models.CharField(
        max_length=25,
        choices=PROPERTY_TYPES,
        default="Apartment",
        blank=False,
        null=False,
    )

    def __str__(self) -> str:
        return self.name

    class Meta:
        verbose_name_plural = _("Categories")


class Heating(models.Model):
    type = models.CharField(
        max_length=25,
        choices=HEATING_CHOICES,
        default="No heating",
        blank=False,
        null=False,
    )

    def __str__(self) -> str:
        return self.type

    class Meta:
        verbose_name_plural = _("Heating types")


class Parking(models.Model):
    type = models.CharField(
        max_length=25,
        choices=PARKING_TYPE,
        default="Parking on the street",
        blank=False,
        null=False,
    )

    def __str__(self) -> str:
        return self.type

    class Meta:
        verbose_name_plural = _("Parking types")


class Property(models.Model):
    title = models.CharField(
        max_length=250,
        verbose_name="title",
    )
    price = models.CharField(
        "price",
        max_length=10,
    )
    province = models.CharField(
        "province",
        max_length=50,
        choices=IL_LIST,
        default="Antalya",
        blank=False,
        null=False,
    )
    district = models.CharField(
        "district",
        max_length=50,
        choices=ANTALYA_DIST_LIST,
        blank=True,
        null=True,
    )
    address = models.CharField(
        "address",
        max_length=250,
        blank=True,
        null=True,
    )
    floor_number = models.DecimalField(
        "floor_number",
        max_digits=2,
        decimal_places=0,
        default=0,
    )
    total_floors = models.DecimalField(
        "total_floors",
        max_digits=2,
        decimal_places=0,
        default=0,
    )
    parking = models.ForeignKey(
        Parking,
        on_delete=models.CASCADE,
        null=False,
        default=[1],
        verbose_name="parking",
    )
    rooms = models.CharField(
        "rooms",
        max_length=200,
    )
    area = models.CharField(
        "area",
        max_length=200,
    )
    heating = models.ForeignKey(
        Heating,
        on_delete=models.CASCADE,
        null=False,
        default=[1],
        verbose_name="heating",
    )
    elevator = models.CharField(
        "elevator",
        max_length=50,
        choices=ELEVATOR,
        default="No",
        blank=False,
        null=False,
    )
    frontage = models.CharField(
        "frontage",
        max_length=50,
        choices=FRONTAGE,
        blank=True,
        null=True,
    )
    iskan = models.CharField(
        max_length=50,
        choices=ISKAN,
        default="Yes",
        blank=True,
        null=True,
    )
    expertise = models.CharField(
        "expertise",
        max_length=50,
        choices=EXPERTISE,
        default="Yes",
        blank=True,
        null=True,
    )
    residence_permit = models.CharField(
        "residence_permit",
        max_length=50,
        choices=RESIDENCE_PERMIT,
        default="Not possible",
        blank=True,
        null=True,
    )
    description = models.TextField(
        "description",
    )
    en_description = models.TextField(
        "description",
        default="",
    )
    tr_description = models.TextField(
        "description",
        default="",
    )
    ru_description = models.TextField(
        "description",
        default="",
    )
    de_description = models.TextField(
        "description",
        default="",
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        null=False,
        default=[1],
        verbose_name="category",
    )
    type_of_deal = models.CharField(
        "type_of_deal",
        max_length=10,
        choices=DEAL_TYPES,
        blank=False,
        null=False,
        default="SALE",
    )
    active = models.BooleanField(
        "active",
        default=True,
    )
    bookmark = models.ManyToManyField(
        User,
        related_name="bookmarks",
        blank=True,
        verbose_name="bookmark",
    )
    created_at = models.DateTimeField(
        "created_at",
        auto_now_add=True,
    )
    updated_at = models.DateTimeField(
        "updated_at",
        auto_now=True,
    )

    def __str__(self):
        return (
            "ID"
            + " "
            + str(self.id)
            + " | "
            + str(self.title)
            + " | "
            + _("Created at: ")
            + str(self.created_at)[:19]
            + " | "
            + _("Updated at: ")
            + str(self.updated_at)[:19]
        )

    class Meta:
        ordering = ("-created_at",)
        verbose_name_plural = _("Property list")


class Photo(models.Model):
    property = models.ForeignKey(
        Property,
        on_delete=models.CASCADE,
        related_name="photos",
    )
    photo = models.ImageField(upload_to="photos/")


class Blog(models.Model):
    title = models.CharField(
        max_length=255,
    )
    text = models.TextField()
    en_title = models.CharField(
        max_length=255,
        blank=True,
        null=True,
    )
    en_text = models.TextField(
        blank=True,
        null=True,
    )
    tr_title = models.CharField(
        max_length=255,
        blank=True,
        null=True,
    )
    tr_text = models.TextField(
        blank=True,
        null=True,
    )
    ru_title = models.CharField(
        max_length=255,
        blank=True,
        null=True,
    )
    ru_text = models.TextField(
        blank=True,
        null=True,
    )
    de_title = models.CharField(
        max_length=255,
        blank=True,
        null=True,
    )
    de_text = models.TextField(
        blank=True,
        null=True,
    )
    active = models.BooleanField(
        default=True,
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
    )
    updated_at = models.DateTimeField(
        auto_now=True,
    )

    def __str__(self) -> str:
        return (
            self.title
            + " | "
            + _("Created at: ")
            + str(self.created_at)[:19]
            + " | "
            + _("Updated at: ")
            + str(self.updated_at)[:19]
        )


class BlogPhoto(models.Model):
    blog = models.ForeignKey(
        Blog,
        on_delete=models.CASCADE,
        related_name="blog_images",
    )
    image = models.ImageField(upload_to="blog_images/")


class Team(models.Model):
    name = models.CharField(
        max_length=255,
    )
    ava = models.ImageField(
        default=None,
        upload_to="teammates",
        blank=True,
        null=True,
    )
    phone = models.CharField(
        max_length=20,
        blank=True,
        null=True,
    )
    email = models.CharField(
        max_length=255,
        blank=True,
        null=True,
    )
    bio = models.TextField(
        blank=True,
        null=True,
    )
    active = models.BooleanField(
        default=True,
    )

    def __str__(self) -> str:
        return self.name + " | " + str(self.phone) + " | " + str(self.email)

my_project/my_site/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import get_user_model

from .models import Property, Photo, Blog, BlogPhoto, Team

from django.forms.models import inlineformset_factory


class SignupForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ("email", "phone", "first_name", "last_name", "password1", "password2")

    email = forms.CharField(
        widget=forms.EmailInput(attrs={"placeholder": "Your Email"})
    )
    phone = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "Your Phone"}))
    first_name = forms.CharField(
        widget=forms.TextInput(attrs={"placeholder": "Your First name"})
    )
    last_name = forms.CharField(
        widget=forms.TextInput(attrs={"placeholder": "Your Last name"})
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder": "Your Password"})
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder": "Repeat Password"})
    )


class EditUserForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ("first_name", "last_name", "email", "phone", "password1", "password2")

    first_name = forms.CharField(
        widget=forms.TextInput(attrs={"placeholder": "Your First name"})
    )
    last_name = forms.CharField(
        widget=forms.TextInput(attrs={"placeholder": "Your Last name"})
    )
    email = forms.CharField(
        widget=forms.EmailInput(attrs={"placeholder": "Your Email"})
    )
    phone = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "Your Phone"}))
    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder": "Your Password"})
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder": "Repeat Password"})
    )


class LoginForm(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(attrs={"placeholder": "Your Email"})
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder": "Your Password"})
    )


class NewPropertyForm(forms.ModelForm):
    class Meta:
        model = Property

        fields = (
            "title",
            "price",
            "province",
            "district",
            "address",
            "floor_number",
            "total_floors",
            "parking",
            "rooms",
            "area",
            "heating",
            "elevator",
            "frontage",
            "iskan",
            "expertise",
            "residence_permit",
            "description",
            "category",
            "type_of_deal",
            "active",
        )

        widgets = {
            "title": forms.TextInput(),
            "price": forms.TextInput(),
            "province": forms.TextInput(),
            "district": forms.Select(),
            "address": forms.TextInput(),
            "floor_number": forms.TextInput(),
            "total_floors": forms.TextInput(),
            "parking": forms.Select(),
            "rooms": forms.TextInput(),
            "area": forms.TextInput(),
            "heating": forms.Select(),
            "elevator": forms.Select(),
            "frontage": forms.Select(),
            "iskan": forms.Select(),
            "expertise": forms.Select(),
            "residence_permit": forms.Select(),
            "description": forms.Textarea(),
            "category": forms.Select(),
            "type_of_deal": forms.Select(),
            "active": forms.CheckboxInput(),
        }


class EditPropertyForm(forms.ModelForm):
    class Meta:
        model = Property

        fields = (
            "title",
            "price",
            "province",
            "district",
            "address",
            "floor_number",
            "total_floors",
            "parking",
            "rooms",
            "area",
            "heating",
            "elevator",
            "frontage",
            "iskan",
            "expertise",
            "residence_permit",
            "description",
            "category",
            "type_of_deal",
            "active",
        )

        widgets = {
            "title": forms.TextInput(),
            "price": forms.TextInput(),
            "province": forms.TextInput(),
            "district": forms.Select(),
            "address": forms.TextInput(),
            "floor_number": forms.TextInput(),
            "total_floors": forms.TextInput(),
            "parking": forms.Select(),
            "rooms": forms.TextInput(),
            "area": forms.TextInput(),
            "heating": forms.Select(),
            "elevator": forms.Select(),
            "frontage": forms.Select(),
            "iskan": forms.Select(),
            "expertise": forms.Select(),
            "residence_permit": forms.Select(),
            "description": forms.Textarea(),
            "category": forms.Select(),
            "type_of_deal": forms.Select(),
            "active": forms.CheckboxInput(),
        }


class PhotoForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = ["photo"]


PhotoFormSet = inlineformset_factory(
    Property, Photo, form=PhotoForm, extra=20, can_delete=True
)


class NewBlogPostForm(forms.ModelForm):

    class Meta:
        model = Blog
        fields = (
            "title",
            "text",
            "active",
        )
        widgets = {
            "title": forms.TextInput(),
            "text": forms.Textarea(),
            "active": forms.CheckboxInput(),
        }


class EditBlogPostForm(forms.ModelForm):

    class Meta:
        model = Blog
        fields = (
            "title",
            "text",
            "en_title",
            "en_text",
            "tr_title",
            "tr_text",
            "ru_title",
            "ru_text",
            "de_title",
            "de_text",
            "active",
        )
        widgets = {
            "title": forms.TextInput(),
            "text": forms.Textarea(),
            "en_title": forms.TextInput(),
            "en_text": forms.Textarea(),
            "tr_title": forms.TextInput(),
            "tr_text": forms.Textarea(),
            "ru_title": forms.TextInput(),
            "ru_text": forms.Textarea(),
            "de_title": forms.TextInput(),
            "de_text": forms.Textarea(),
            "active": forms.CheckboxInput(),
        }


class BlogPhotoForm(forms.ModelForm):
    class Meta:
        model = BlogPhoto
        fields = ["image"]


BlogPhotoFormSet = inlineformset_factory(
    Blog, BlogPhoto, form=BlogPhotoForm, extra=1, can_delete=True
)


class NewTeamMateForm(forms.ModelForm):
    class Meta:
        model = Team
        fields = (
            "name",
            "ava",
            "phone",
            "email",
            "bio",
            "active",
        )
        widgets = {
            "name": forms.TextInput(),
            "ava": forms.FileInput(),
            "phone": forms.TextInput(),
            "email": forms.TextInput(),
            "bio": forms.TextInput(),
            "active": forms.CheckboxInput(),
        }

my_project/my_site/templates/my_site/base.html
{% load static i18n %}

<!DOCTYPE HTML>

<html>

    <head>

        <meta name="viewport" charset='UTF-8' content="width=device-width, initial-scale=1.0">

        <title>HAKAN ARSLAN EMLAK</title>

        <link rel="shortcut icon" type="image/png" href="{% static 'my_site/favicon.ico' %}"/>

        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">

        <link rel="stylesheet" type="text/css" href="{% static 'my_site/base.css' %}">

    </head>

    <body>
            
        <div class='header'>

            <a href="{% url 'my_site:index' %}">

                <div class="logo">

                    <img class="logo_img" src={% static 'my_site/logo_img_2.png' %}/>

                    

                </div>

            </a>

            <a href="{% url 'my_site:index' %}">

                <h1 class='logo_text'>HAKAN ARSLAN EMLAK</h1>

            </a>

            <div class="login_signup_buttons" id="login_signup_buttons">

                {% if request.user.is_authenticated %}

                    <div class='login_signup_authenticated'>

                        {% if request.user.is_staff %}
                        <a class='button' id="button" href="{% url 'my_site:dashboard' %}">{% trans 'DASHBOARD' %}</a>
                        {% endif %}

                        <a class='button' id="button" href="{% url 'my_site:profile' request.user.id %}">{% trans 'MY PROFILE' %}</a>

                        <a class='button' id="signup" href="{% url 'logout' %}">{% trans 'LOG OUT' %}</a>

                    </div>

                    {% if user.first_name %}
                        
                        <p class="welcome_message">{% trans 'Welcome,' %} {{ user.first_name }}!</p>

                    {% else %}

                        <p class="welcome_message">{% trans 'Welcome,' %} {{ user.email }}!</p>
                    
                    {% endif %}

                {% else %}

                    <a class="button" id="signup" href="{% url 'my_site:signup' %}">{% trans 'Sign up' %}</a>

                    <a class="button" id="button" href="{% url 'my_site:user_login' %}">{% trans 'Log in' %}</a>                    

                {% endif %}

            </div>                

        </div>

        <div class='main_menu_container'>

            <div class="imgContainer">

                <img class='item item_show' src={% static 'my_site/image_1r.jpg' %} />

                <img class='item' src={% static 'my_site/image_5r.jpg' %} />

                <img class='item' src={% static 'my_site/image_11r.jpg' %} />

                <img class='item' src={% static 'my_site/image_12r.jpg' %} />

                <img class='item' src={% static 'my_site/image_13r.jpg' %} />

            </div>

            <script>

                const elem = document.querySelectorAll('.imgContainer .item');
                let currentIndex = 0;

                setInterval(function() {
                    elem.forEach(item => item.classList.remove('item_show'));
                    elem[currentIndex].classList.add('item_show');

                    currentIndex = (currentIndex + 1) % elem.length;
                    }, 5000);
                
            </script>
       
            <div class='main_menu'>

                <a class='button_menu' href="{% url 'my_site:property_for_sale_list_view' %}">{% trans 'FOR SALE' %}</a>

                <a class='button_menu' href="{% url 'my_site:property_for_rent_list_view' %}">{% trans 'FOR RENT' %}</a>

                <a class='button_menu' href="{% url 'my_site:blog' %}">{% trans 'BLOG' %}</a>

                <a class='button_menu' href="{% url 'my_site:team' %}">{% trans 'OUR TEAM' %}</a>
                
                <a class='button_menu' href="{% url 'my_site:contacts' %}">{% trans 'CONTACTS' %}</a>

            </div>                            
        
        </div>

        <div class='search_bar_container'>

            <div class='search_bar_form_container'>

                <form class='search_bar' method=POST action={% url 'my_site:search_result' %}>

                    {% csrf_token %}

                    <input placeholder={% trans 'Search' %} name='searched'>

                    <button class='search_button' id="search_button" type='submit'>{% trans 'SEARCH' %}</button>

                </form>
            
            </div>

            <div class='search_bar_form_container'>

                <form action="{% url 'set_language' %}" method="post">

                    {% csrf_token %}

                    <input type="hidden" name="next" value="{{ request.path }}">

                    {% get_current_language as current_language %}

                    {% get_available_languages as available_languages %}

                    <button class='button' style="padding: 10px; min-width: fit-content;" type="submit" name="language" value="{% if current_language == 'tr' %}en{% elif current_language == 'en' %}ru{% elif current_language == 'ru' %}de{% elif current_language == 'de' %}tr{% endif %}">

                        {% if current_language == 'tr' %}

                        🇹🇷

                        {% elif current_language == 'en' %}

                        🇺🇸

                        {% elif current_language == 'ru' %}

                        🇷🇺

                        {% elif current_language == 'de' %}

                        🇩🇪

                        {% endif %}
                        
                    </button>
                    
                </form>
            
            </div>

        </div>
        <div class='exchange_rates_container'>
            <div id='exchange_rates' class='exchange_rates'>            

            </div>
        </div>
        <div class='currency_selector_container'>
            <h5>{% trans 'Select currency' %}:
            <select id="currency_selector" class='currency_selector'>
                <option value="TRY">TRY</option>
                <option value="USD">USD</option>
                <option value="EUR">EUR</option>
                <option value="RUB">RUB</option>
            </select>
            </h5>
        </div>

        <script>
            document.addEventListener('DOMContentLoaded', function() {
                const currencySwitcher = document.getElementById('currency_selector');

                // Get the saved currency from the cookie and set it as the selected option
                const savedCurrency = getCookie('selectedCurrency');
                if (savedCurrency) {
                    currencySwitcher.value = savedCurrency;
                    switchCurrency(savedCurrency);
                }

                currencySwitcher.addEventListener('change', function() {
                    const newCurrency = this.value;
                    switchCurrency(newCurrency);
                    // Save the selected currency in a cookie
                    setCookie('selectedCurrency', newCurrency, 7); // Cookie expires in 7 days
                });

                function switchCurrency(currency) {
                    const prices = document.querySelectorAll('.price');

                    prices.forEach(priceElement => {
                        let newPrice;
                        switch(currency) {
                            case 'USD':
                                newPrice = priceElement.dataset.usd;
                                break;
                            case 'EUR':
                                newPrice = priceElement.dataset.eur;
                                break;
                            case 'RUB':
                                newPrice = priceElement.dataset.rub;
                                break;
                            default:
                                newPrice = priceElement.dataset.try;
                        }

                        const priceValueElement = priceElement.querySelector('.price-value');
                        if (priceValueElement) {
                            priceValueElement.textContent = newPrice;
                        }

                        // Update the currency symbol
                        const currencySymbol = currency === 'TRY' ? 'TL' : currency;

                        // Check if the price contains additional text
                        const hasAdditionalText = priceElement.textContent.includes('/');

                        if (hasAdditionalText) {
                            // If there's additional text, replace just the currency symbol
                            priceElement.innerHTML = priceElement.innerHTML.replace(/TL|USD|EUR|RUB/, currencySymbol);
                        } else {
                            // If it's a simple price, replace the whole content
                            priceElement.innerHTML = `<b>${newPrice} ${currencySymbol}</b>`;
                        }
                    });
                }

                function setCookie(name, value, days) {
                    let expires = "";
                    if (days) {
                        const date = new Date();
                        date.setTime(date.getTime() + (days * 24 * 60 * 60 * 1000));
                        expires = "; expires=" + date.toUTCString();
                    }
                    document.cookie = name + "=" + (value || "") + expires + "; path=/";
                }

                function getCookie(name) {
                    const nameEQ = name + "=";
                    const ca = document.cookie.split(';');
                    for(let i = 0; i < ca.length; i++) {
                        let c = ca[i];
                        while (c.charAt(0) == ' ') c = c.substring(1, c.length);
                        if (c.indexOf(nameEQ) == 0) return c.substring(nameEQ.length, c.length);
                    }
                    return null;
                }
            });
        </script>
        


        <script>
            document.addEventListener('DOMContentLoaded', function() {
                fetchExchangeRates();
            });

            function fetchExchangeRates() {
                fetch('{% url "my_site:exchange_rates" %}')
                    .then(response => response.text())
                    .then(html => {
                        document.getElementById('exchange_rates').innerHTML = html;
                    });
            }
        </script>

        {% block content %}

        {% endblock %}

        <footer>
            
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

            <div class="footer">
                <div class="row">
                    <a href="https://www.facebook.com/profile.php?id=100043587060070" target="_blank"><i class="fa fa-facebook"></i></a>
                    <a href="https://www.instagram.com/antalya.hakan.arslan.emlak/" target="_blank"><i class="fa fa-instagram"></i></a>
                    <a href="#" target="_blank"><i class="fa fa-youtube"></i></a>                    
                    <a href="https://t.me/+905376321145" target="_blank"><i class="fa fa-telegram"></i></a>
                    <a href="https://wa.me/905376321145" target="_blank"><i class="fa fa-whatsapp"></i></a>
                </div>

                <!--<div class="row">
                    <ul>
                        <li><a href="{% url 'my_site:contacts' %}">{% trans 'Contact us' %}</a></li>
                        <li><a href="#">{% trans 'Privacy Policy' %}</a></li>
                        <li><a href="#">{% trans 'Terms & Conditions' %}</a></li>
                    </ul>
                </div>-->

                <div class="row">
                    <b>HAKAN ARSLAN EMLAK</b> Copyright © 2023 - All rights reserved || Created by: <a href="mailto:egor.shabalin.wd@gmail.com"><b>Egor Shabalin</b></a>
                </div>
            </div>
        </footer>

        <div id="cookieConsent" style="display:none;">
            <p>{% trans 'This website uses cookies to ensure you get the best experience on our website.' %}</p>
            <button onclick="acceptCookies()">{% trans 'Got it!' %}</button>
        </div>

        <script>
        function setCookie(name, value, days) {
            var expires = "";
            if (days) {
                var date = new Date();
                date.setTime(date.getTime() + (days*24*60*60*1000));
                expires = "; expires=" + date.toUTCString();
            }
            document.cookie = name + "=" + (value || "")  + expires + "; path=/";
        }

        function getCookie(name) {
            var nameEQ = name + "=";
            var ca = document.cookie.split(';');
            for(var i=0;i < ca.length;i++) {
                var c = ca[i];
                while (c.charAt(0)==' ') c = c.substring(1,c.length);
                if (c.indexOf(nameEQ) == 0) return c.substring(nameEQ.length,c.length);
            }
            return null;
        }

        function acceptCookies() {
            setCookie('cookieConsent', 'accepted', 365);
            document.getElementById('cookieConsent').style.display = 'none';
        }

        window.onload = function() {
            if (!getCookie('cookieConsent')) {
                document.getElementById('cookieConsent').style.display = 'block';
            }
        }
        </script>

    </body>

</html>

my_project/my_site/templates/my_site/thank_you.html
{% extends 'my_site/base.html' %}

{% load i18n %}

{% block content %}

<div class="login_signup">

    <center>

        <h2>{% trans "Thank you! We got your request!" %}</h2>

    </center>

</div>

{% endblock %}